spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 1h
          cache-public: true
        use-last-modified: true
    error:
      include-message: never
      include-binding-errors: never
      include-stacktrace: never
      include-exception: false
      include-path: never
      whitelabel:
        enabled: false

server:
  compression:
    enabled: true
